---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Check tribe/squad labels'
    validate:
      - do: label
        json_http_api:
          regex: 'tribe: ([a-z]+[a-z\-]+)'
          endpoint: https://hellodev.hellofresh.io/api/catalog/entities/by-name/Group/hellotech/$1
