---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Check tribe/squad labels'
    validate:
      - do: label
        json_http_api:
          regex: 'tribe: (?<tribe>.*)|squad: (?<squad>.*)'
          endpoint: https://hellodev.hellofresh.io/api/catalog/entities/by-name/Group/{{tribe}}/{{squad}}
