---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Check tribe/squad labels'
    validate:
      - do: label
        http_api:
          endpoint: https://hellodev.hellofresh.io/api/catalog/entities/by-name/Group/adtech/leads
